//Winter 2024. EECS 280 Lab 6 Section 029. Alan Sun and Shayla Doan.
//In-Class Demonstration of Inheritance and Polymorphism
#include "Shapes.hpp"
#include <iostream>
#include <string>
#include <cassert>

using namespace std;


//INSTRUCTIONS: There are three errors in Shapes.hpp that prevent
//              the program from compiling. Find them and fix them.


/* -------------------------------------------------------------------------- */
/*                    DO NOT EDIT THIS FILE BELOW (please)                    */
/* -------------------------------------------------------------------------- */

int main() {
    //ask students why we can't do this
    //Shape bad_shape; //why is this not compiling??

    Shape* s = new Circle(3); //why doesn't this work?
    cout << "Circle Area: " << s->get_area() << endl;
    cout << "Circle Perimeter: " << s->get_perimeter() << endl;
    delete s;
    s = nullptr;

    Rectangle* r = new Square(10);
    cout << "Square Area: " << r->get_area() << endl;
    cout << "Square Perimeter: " << r->get_perimeter() << endl;
    delete r;

    //what will print? We never put "virtual" in front of
    //the Rectangle functions, so will this run the Rectangle
    //version or the Random versions?
    r = new Random();   //"delete r" deletes the object at r, not the ptr
    cout << "Random Area: " << r->get_area() << endl;
    cout << "Random Perimeter: " << r->get_perimeter() << endl;
    delete r;


    return 0;
}